server:
  port: 31000

spring:
  application:
    name: struggler-gateway
  security:
    user:
      name: admin
      password: 123456
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

eureka:
  instance:
    prefer-ip-address: true
    # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 90
    # 心跳时间，即服务续约间隔时间（缺省为30s
    lease-renewal-interval-in-seconds: 30
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
  client:
    service-url:
      defaultZone: http://localhost:31001/eureka/

#---------------------OAuth2---------------------
security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/auth/oauth/token
      user-authorization-uri: http://localhost:${server.port}/auth/oauth/authorize
      client-id: android
      client-secret: android
    resource:
      user-info-uri:  http://localhost:${server.port}/auth/api/userInfo
      prefer-token-info: false
      token-info-uri: http://localhost:${server.port}/auth/oauth/check_token
zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: STRUGGLER-AUTHORIZATION-SERVER
      sensitiveHeaders: "*"
    sys:
      path: /sysmanage/**
      serviceId: STRUGGLER-SYS-MANAGE
      sensitiveHeaders: "*"
  retryable: false
  ignored-services: "*"
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000 #socket超时
  add-proxy-headers: true
  ribbon:
    eager-load:
      enabled: true

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 50000
management:
  endpoints:
    web:
      exposure:
        include: '*'
