server:
  port: 31002

spring:
  application:
    name: struggler-authorization-server
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
#    url: jdbc:mysql://127.0.0.1:3306/platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root1234
  druid:
    initialSize: 5 #初始化连接大小
    minIdle: 5     #最小连接池数量
    maxActive: 20  #最大连接池数量
    maxWait: 60000 #获取连接时最大等待时间，单位毫秒
    timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000   #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 from DUAL  #测试连接
    testWhileIdle: true                  #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
    testOnBorrow: false                  #获取连接时执行检测，建议关闭，影响性能
    testOnReturn: false                  #归还连接时执行检测，建议关闭，影响性能
    poolPreparedStatements: false        #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
    maxPoolPreparedStatementPerConnectionSize: 20 #开启poolPreparedStatements后生效
    filters: stat,wall,log4j #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
    connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000' #通过connectProperties属性来打开mergeSql功能;
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.struggler.authorization.model,com.struggler.common.model
  mapper-locations: classpath:mybatis/*.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    logic-delete-value: -1
    logic-not-delete-value: 0

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #开启驼峰命名,l_name -> lName
    jdbc-type-for-null: NULL
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    cache-enabled: true #开启二级缓存
    call-setters-on-nulls: true #map空列不显示问题


eureka:
  instance:
    prefer-ip-address: true
    # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 90
    # 心跳时间，即服务续约间隔时间（缺省为30s
    lease-renewal-interval-in-seconds: 30
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
  client:
    service-url:
      defaultZone: http://localhost:31001/eureka/
logging:
  pattern:
    console: "%-5level %logger{36} %d - %msg%n" #     定义打印的日志格式
  #    dateformat: #设置日志日期格式
  #    file: #定义输出到日志文件的日志格式
  #  config: #日志配置文件的位置。例如，classpath:logback.xml。
  #file: E:/sell/sell.log #设置保存日志的日志文件
  #    max-history:
  #    max-size: #设置日志文件最大大小 #设置日志等级
  #  path: / #日志文件的位置，例如/var/log
  register-shutdown-hook: false #当初始化日志系统时，为其注册一个关闭钩子。
  level:
    configuredLevel: debug
    effectiveLevel: debug
